---

- name: Limit to the whole play to just Windows.
  ansible.builtin.import_tasks: windows.yml
  when: ansible_os_family == 'Windows'
  tags:
    - main
    - schannel
    - security
    - windows
