---

- name: Set MD5.
  ansible.windows.win_regedit:
    path: HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Hashes\MD5
    name: Enabled
    type: dword
    data: "{{ schannel_md5 | ternary('4294967295', '0') }}"
    state: present
  tags:
    - md5

- name: Set SHA-1.
  ansible.windows.win_regedit:
    path: HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Hashes\SHA
    name: Enabled
    type: dword
    data: "{{ schannel_sha1 | ternary('4294967295', '0') }}"
    state: present
  tags:
    - sha1

- name: Set SHA-256.
  ansible.windows.win_regedit:
    path: HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Hashes\SHA256
    name: Enabled
    type: dword
    data: "{{ schannel_sha256 | ternary('4294967295', '0') }}"
    state: present
  tags:
    - sha256

- name: Set SHA-384.
  ansible.windows.win_regedit:
    path: HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Hashes\SHA384
    name: Enabled
    type: dword
    data: "{{ schannel_sha384 | ternary('4294967295', '0') }}"
    state: present
  tags:
    - sha384

- name: Set SHA-512.
  ansible.windows.win_regedit:
    path: HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Hashes\SHA512
    name: Enabled
    type: dword
    data: "{{ schannel_sha512 | ternary('4294967295', '0') }}"
    state: present
  tags:
    - sha512
