---

name: Release
'on':
  push:
    tags:
      - '*'

defaults:
  run:
    working-directory: 'deekayen.schannel'

jobs:

  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v4.1.1
        with:
          path: 'deekayen.schannel'

      - name: GitHub Environment Variables Action
        uses: FranzDiebold/github-env-vars-action@v2.7.0

      - name: Trigger a new import on Galaxy.
        run: ansible-galaxy role import --branch $CI_REF_NAME --api-key ${{ secrets.GALAXY_API_KEY }} $CI_REPOSITORY_OWNER $CI_REPOSITORY_NAME
